### ISSUE TITLE
at Home Page， it should need maxbtn, closeBtn, and etc.

### ISSUE THREAD

**Issue by mowangshuying** [mentalfl0w/RibbonUI#3]
![image](https://github.com/user-attachments/assets/a4aba0c9-e7e1-48bd-8572-7c8cc974bd84)

**Comment by mowangshuying** [comment]
此页面是否需要添加，最大化，最小化等按钮的标题栏，类似主页面中的标题栏。

**Comment by mentalfl0w** [comment]
macOS下默认是有的，忘记给Windows和Linux添加了，感谢建议！已更新。
