### ISSUE TITLE
如何添加新的组件

### ISSUE THREAD

**Issue by MoonBite666** [mentalfl0w/RibbonUI#4]
比如我想添加RibbonToolBar.qml
我在lib_source/qml/Qt6和lib_source/qml/Qt5内分别新建了RibbonToolBar.qml，复制粘贴自RibbonBottomBar.qml，将最后一行修改为：
`Component.onCompleted: Window.window.toolBar = root`
再为RibbonWindow.qml添加属性：
`property var toolBar`
并且在lib_source/CMakeLists.txt中添加了这个文件：
```
set(qml_files RibbonTabBar.qml RibbonTabButton.qml RibbonView.qml RibbonToolBar.qml
    #......
)
```
但是编译过后也没有出现相关的文件，其它工程也无法引用到RibbonToolBar。
请问一下还应该在哪里添加上这个自定义的组件。非常感谢！

**Comment by mentalfl0w** [comment]
我看这个步骤是没有问题的，只需要在`lib_source/CMakeLists.txt`这里的`set(qml_files`中添加这个文件就可以了，大致步骤都没有问题，请问方便将更改提交到你的fork仓库分支，我clone下来看看具体是什么问题吗？

**Comment by MoonBite666** [comment]
已经提交至[fork](https://github.com/MoonBite666/RibbonUI)，非常感谢

**Comment by mentalfl0w** [comment]
我这边测试了一下没问题，是不是Qt Creator在编译完成后显示找不到`RibbonToolBar`？这个需要手动重制一下代码模型：
<img width="625" alt="image" src="https://github.com/user-attachments/assets/b3455ea2-d09c-4bd7-a844-b1b08b9715ee">
编译过程中也处理了这个文件：
<img width="891" alt="image" src="https://github.com/user-attachments/assets/e3957e30-7ef0-418f-bd32-e0c95a8cb4d2">

**Comment by MoonBite666** [comment]
确实是没有重置导致的，我这边用的CLion，把build清空再编译一次就好了。
