### ISSUE TITLE
RibbonPopup 圆角不对.

### ISSUE THREAD

**Issue by mowangshuying** [mentalfl0w/RibbonUI#7]
![image](https://github.com/user-attachments/assets/d0aca21e-d4ea-425b-895d-f76e657ab490)

**Comment by mowangshuying** [comment]
RibbonPopUp圆角太大了，太突兀了.

**Comment by mentalfl0w** [comment]
我也觉得，之前设计的时候先初步定了一个数值，后期没做统一，目前已修改，感谢建议！
